#ifndef DEFINE_H
#define DEFINE_H


#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 480 


#define MENU_START_X 160
#define MENU_START_Y 360
#define MENU_START_WIDTH 160
#define MENU_START_HEIGHT 60


#define PLATFORM_WIDTH 60
#define PLATFORM_HEIGHT 20
#define LADDER_WIDTH 20


#define FRAMES_PER_SECOND 20


#define MARIO_WIDTH 14
#define MARIO_HEIGHT 27

#define MARIO_RIGHT 0
#define MARIO_LEFT 1

#define MARIO_START_X 50
#define MARIO_START_Y 525


#define FIRE_WIDTH 14
#define FIRE_HEIGHT 27

#define FIRE_RIGHT 0
#define FIRE_LEFT 1

#define FIRE_START_X 300
#define FIRE_START_Y 525


#define PEACH_WIDTH 28
#define PEACH_HEIGHT 38

#define PEACH_LEFT_LIMIT 200
#define PEACH_RIGHT_LIMIT 260

#define PEACH_START_X 200
#define PEACH_Y 100


#define DK_WIDTH 62
#define DK_HEIGHT 120

#define DK_START_X 30
#define DK_START_Y 108

#endif
